name: ci

on:
  push:
    branches:
      - master

jobs:
  fern-generate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check

      - name: Publish Python SDK PR
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --group python-sdk-staging --log-level debug
