name: 'Fern Check'

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref'
        required: true
        type: string
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ inputs.ref || github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  Check:
    name: Fern Check
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_PAT }}
          ref: "${{ inputs.ref || github.event.pull_request.head.sha }}"

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Download Fern
        run: npm install -g fern-api@latest

      - name: Check Fern API is valid
        run: fern check
