name: Preview SDKs

on:
  pull_request:

env:
  POETRY_VERSION: "2.1.3"

jobs:
  preview-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Preview Python SDK 
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group python-sdk-staging --preview --log-level debug
    
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install poetry"
        run: pipx install "poetry==${{ env.POETRY_VERSION }}"

      - name: Compile
        run: | 
          cd fern/.preview/fern-python-sdk
          poetry install          
          poetry run mypy .
