name: "Publish Docs"

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}

jobs:
  publish:
    name: "Publish Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate and Publish
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs
